services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: local_django
    platform: linux/x86_64
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
  frontend:
    image: mhart/alpine-node:latest
    container_name: local_frontend
    tty: true
    volumes: [./frontend:/app]
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
