# Generated by Django 4.2.2 on 2023-07-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_integration", "0002_index_customer_alter_index_index_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="index_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
