# Generated by Django 4.2.3 on 2023-07-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("llm_integration", "0003_alter_index_index_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "uploaded_file_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=400)),
                ("description", models.CharField(max_length=100)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llm_integration.index",
                    ),
                ),
            ],
        ),
    ]
