# Generated by Django 4.2.3 on 2023-07-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_integration", "0004_uploadedfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
