# Generated by Django 4.2.2 on 2023-07-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_remove_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=300),
        ),
    ]
